# ---------- Base (uv binary) ----------
FROM ghcr.io/astral-sh/uv:0.5.11 AS uv

# ---------- Builder ----------
FROM python:3.12-slim AS builder

# Python runtime settings
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PORT=8000 \
    GUNICORN_WORKERS=2

ARG STAGE=prod
ENV STAGE=${STAGE}

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
        gcc \
        libpq-dev \
        python3-dev \
    rm -rf /var/lib/apt/lists/*

# Copy uv binary
COPY --from=uv /uv /uvx /bin/

WORKDIR /ms_app

# Create virtual environment
RUN python -m venv /ms_app/.venv

ENV PATH="/ms_app/.venv/bin:$PATH"

COPY pyproject.toml uv.lock ./

# Install dependencies (cached)
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev --no-install-project

# Copy app code
COPY . .

# Install project itself
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev

# ---------- Runtime ----------
FROM python:3.12-slim

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
        libpq5 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /ms_app

# Copy virtual environment from builder
COPY --from=builder /ms_app/.venv /ms_app/.venv

# Copy app code
COPY --from=builder /ms_app /ms_app

# Activate venv
ENV PATH="/ms_app/.venv/bin:$PATH"

# Make entrypoint executable
# RUN chmod +x /ms_app/docker_entrypoint.sh
RUN chmod +x docker-entrypoint.sh

# Create a non-root user and adjust permissions
RUN useradd -m -u 10001 -s /usr/sbin/nologin appuser && \
    chown -R appuser:appuser /ms_app
USER appuser

# Expose the application port
EXPOSE 8000

ENTRYPOINT ["./docker-entrypoint.sh"]


#CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]