"""create initial tables

Revision ID: d9c3c54517d4
Revises: 
Create Date: 2026-03-10 15:03:20.803281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9c3c54517d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clean_rooms',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('serial_number', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.String(length=20), server_default=sa.text("'processing'::character varying"), nullable=True),
    sa.Column('status', sa.Enum('available', 'sterilizing', 'in_use', 'maintenance', 'sterilized', name='room_status_enum'), server_default=sa.text("'available'::room_status_enum"), nullable=True),
    sa.Column('max_technicians', sa.Integer(), server_default=sa.text('4'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.CheckConstraint("room_type::text = ANY (ARRAY['processing'::character varying, 'packaging'::character varying]::text[])", name='clean_rooms_room_type_check'),
    sa.CheckConstraint('serial_number >= 1 AND serial_number <= 10', name='clean_rooms_serial_number_check'),
    sa.PrimaryKeyConstraint('room_id', name='clean_rooms_pkey'),
    sa.UniqueConstraint('serial_number', name='clean_rooms_serial_number_key')
    )
    op.create_table('donors',
    sa.Column('donor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('znumber', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('other_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('donor_id', name='donors_pkey'),
    sa.UniqueConstraint('znumber', name='donors_znumber_key')
    )
    op.create_table('shifts',
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('shift_id', name='shifts_pkey')
    )
    op.create_table('technicians',
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('technician', 'supervisor', name='tech_role_enum'), server_default=sa.text("'technician'::tech_role_enum"), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.PrimaryKeyConstraint('technician_id', name='technicians_pkey'),
    sa.UniqueConstraint('user_id', name='technicians_user_id_key')
    )
    op.create_table('tissue_categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('num_products', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('category_id', name='tissue_categories_pkey'),
    sa.UniqueConstraint('name', name='tissue_categories_name_key')
    )
    op.create_table('machines',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('centrifuge', 'ultrasonic', name='machine_type_enum'), nullable=True),
    sa.Column('programs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scancode', sa.String(length=50), nullable=True),
    sa.Column('machine_room_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('available', 'in_use', 'maintenance', name='machine_status_enum'), server_default=sa.text("'available'::machine_status_enum"), nullable=True),
    sa.ForeignKeyConstraint(['machine_room_id'], ['clean_rooms.room_id'], name='machines_machine_room_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('machine_id', name='machines_pkey'),
    sa.UniqueConstraint('scancode', name='machines_scancode_key')
    )
    op.create_table('materials',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scancode', sa.String(length=50), nullable=True),
    sa.Column('quantity_available', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('materials_room_id', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['materials_room_id'], ['clean_rooms.room_id'], name='materials_materials_room_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('material_id', name='materials_pkey'),
    sa.UniqueConstraint('scancode', name='materials_scancode_key')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('base_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tissue_categories.category_id'], name='products_category_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('product_id', name='products_pkey')
    )
    op.create_table('room_sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('queue_position', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('status', sa.Enum('planned', 'active', 'completed', 'cleaning', name='session_status_enum'), server_default=sa.text("'planned'::session_status_enum"), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cleaned_at', sa.DateTime(), nullable=True),
    sa.Column('technician_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.donor_id'], name='room_sessions_donor_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['clean_rooms.room_id'], name='room_sessions_room_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], name='room_sessions_shift_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('session_id', name='room_sessions_pkey')
    )
    op.create_index('idx_one_active_session_per_room', 'room_sessions', ['room_id'], unique=True, postgresql_where=sa.text("status = 'active'::session_status_enum"))
    op.create_index('idx_sessions_donor', 'room_sessions', ['donor_id'], unique=False)
    op.create_index('idx_sessions_room', 'room_sessions', ['room_id'], unique=False)
    op.create_index('idx_sessions_status', 'room_sessions', ['status'], unique=False)
    op.create_table('tissues',
    sa.Column('tissue_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('bundle_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('collected', 'planned', 'processed', 'discarded', 'qa_rejected', name='tissue_status_enum'), server_default=sa.text("'collected'::tissue_status_enum"), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tissue_categories.category_id'], name='tissues_category_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.donor_id'], name='tissues_donor_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tissue_id', name='tissues_pkey')
    )
    op.create_index('idx_tissues_donor', 'tissues', ['donor_id'], unique=False)
    op.create_index('idx_tissues_status', 'tissues', ['status'], unique=False)
    op.create_table('tracking_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('tissue', 'process', 'plan', 'session', name='entity_type_enum'), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('collected', 'planned', 'step_completed', 'deviated', 'movement', 'verification', 'session_started', 'session_completed', 'room_cleaned', name='event_type_enum'), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['clean_rooms.room_id'], name='tracking_logs_room_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['technicians.technician_id'], name='tracking_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id', name='tracking_logs_pkey')
    )
    op.create_index('idx_tracking_entity', 'tracking_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_tracking_timestamp', 'tracking_logs', ['timestamp'], unique=False)
    op.create_table('workflows',
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), server_default=sa.text("'production'::character varying"), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('template_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tissue_categories.category_id'], name='workflows_category_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('workflow_id', name='workflows_pkey'),
    sa.UniqueConstraint('category_id', 'name', 'version', name='unique_workflow_version')
    )
    op.create_index('idx_workflows_template', 'workflows', ['template_json'], unique=False)
    op.create_table('production_plans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('tissue_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('planned_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'approved', 'executing', name='plan_status_enum'), server_default=sa.text("'draft'::plan_status_enum"), nullable=True),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='production_plans_product_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tissue_id'], ['tissues.tissue_id'], name='production_plans_tissue_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', name='production_plans_pkey')
    )
    op.create_table('session_technicians',
    sa.Column('session_tech_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('is_lead', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['room_sessions.session_id'], name='session_technicians_session_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.technician_id'], name='session_technicians_technician_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_tech_id', name='session_technicians_pkey'),
    sa.UniqueConstraint('session_id', 'technician_id', name='unique_session_tech')
    )
    op.create_table('processes',
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('template_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tissue_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'completed', 'deviated', name='process_status_enum'), server_default=sa.text("'planned'::process_status_enum"), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['production_plans.plan_id'], name='processes_plan_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['room_sessions.session_id'], name='processes_session_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tissue_id'], ['tissues.tissue_id'], name='processes_tissue_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], name='processes_workflow_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('process_id', name='processes_pkey')
    )
    op.create_index('idx_processes_session', 'processes', ['session_id'], unique=False)
    op.create_index('idx_processes_status', 'processes', ['status'], unique=False)
    op.create_index('idx_processes_tissue', 'processes', ['tissue_id'], unique=False)
    op.create_index('idx_processes_workflow', 'processes', ['workflow_id'], unique=False)
    op.create_table('process_comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['processes.process_id'], name='process_comments_process_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['technicians.technician_id'], name='process_comments_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('comment_id', name='process_comments_pkey')
    )
    op.create_table('verifications',
    sa.Column('verif_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('role_type', sa.String(length=20), nullable=True),
    sa.Column('signed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('signature_url', sa.String(length=500), nullable=True),
    sa.Column('signed_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['processes.process_id'], name='verifications_process_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signed_by_user_id'], ['technicians.technician_id'], name='verifications_signed_by_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('verif_id', name='verifications_pkey')
    )
    op.create_table('workflow_steps',
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('step_num', sa.Integer(), nullable=True),
    sa.Column('initials', sa.String(length=10), nullable=True),
    sa.Column('verified_by_initials', sa.String(length=10), nullable=True),
    sa.Column('spin_program', sa.String(length=20), nullable=True),
    sa.Column('spin_count', sa.Integer(), nullable=True),
    sa.Column('actual_duration', sa.String(length=20), nullable=True),
    sa.Column('temp_start', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_stop', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_compliant', sa.Boolean(), nullable=True),
    sa.Column('na_performed', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('deviation_notes', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('step_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('device_id', sa.String(length=50), nullable=True),
    sa.Column('client_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['processes.process_id'], name='workflow_steps_process_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id', name='workflow_steps_pkey'),
    sa.UniqueConstraint('process_id', 'step_num', name='unique_process_step')
    )
    op.create_index('idx_wf_steps_process_step', 'workflow_steps', ['process_id', 'step_num'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wf_steps_process_step', table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_table('verifications')
    op.drop_table('process_comments')
    op.drop_index('idx_processes_workflow', table_name='processes')
    op.drop_index('idx_processes_tissue', table_name='processes')
    op.drop_index('idx_processes_status', table_name='processes')
    op.drop_index('idx_processes_session', table_name='processes')
    op.drop_table('processes')
    op.drop_table('session_technicians')
    op.drop_table('production_plans')
    op.drop_index('idx_workflows_template', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index('idx_tracking_timestamp', table_name='tracking_logs')
    op.drop_index('idx_tracking_entity', table_name='tracking_logs')
    op.drop_table('tracking_logs')
    op.drop_index('idx_tissues_status', table_name='tissues')
    op.drop_index('idx_tissues_donor', table_name='tissues')
    op.drop_table('tissues')
    op.drop_index('idx_sessions_status', table_name='room_sessions')
    op.drop_index('idx_sessions_room', table_name='room_sessions')
    op.drop_index('idx_sessions_donor', table_name='room_sessions')
    op.drop_index('idx_one_active_session_per_room', table_name='room_sessions', postgresql_where=sa.text("status = 'active'::session_status_enum"))
    op.drop_table('room_sessions')
    op.drop_table('products')
    op.drop_table('materials')
    op.drop_table('machines')
    op.drop_table('tissue_categories')
    op.drop_table('technicians')
    op.drop_table('shifts')
    op.drop_table('donors')
    op.drop_table('clean_rooms')
    # ### end Alembic commands ###
